Script started on 2016年03月13日 (週日) 17時27分23秒
]0;root@kali: ~/sandbox[01;31mroot@kali[00m:[01;34m~/sandbox[00m# git clone https://github.com/glitter2626/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwd
root
/root/sandbox
]0;root@kali: ~/sandbox[01;31mroot@kali[00m:[01;34m~/sandbox[00m# whoami; pwdgit clone https://github.com/glitter2626/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K
user.name=glitter2626
user.email=gercommand@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/glitter2626/test.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
]0;root@kali: ~/sandbox[01;31mroot@kali[00m:[01;34m~/sandbox[00m# git config -l[2Pwhoami; pwdgit clone https://github.com/glitter2626/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;root@kali: ~/sandbox[01;31mroot@kali[00m:[01;34m~/sandbox[00m# exit

Script done on 2016年03月13日 (週日) 17時27分41秒
